apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs
spec:
  storageClassName: nfs-manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem #Block
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.226.172.3
    path: "/var/nfs/jenkins"
